# Generated by Django 5.1.4 on 2024-12-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_voetbalspeler_voetbalspelers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voetbalspelers',
            options={'verbose_name_plural': 'Voetbalspelers'},
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='author',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='voetbalclud',
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='voetbalclub',
            field=models.CharField(default='Onbekend', max_length=100),
        ),
    ]
